### ISSUE TITLE
RegExps 

### ISSUE THREAD

**Issue by Myralllka** [ucu-computer-science/UCU_Linux_Club#34]
make presentation + presentation notes + create homework

**Comment by last-genius** [comment]
Reviewed the presentation, it's awesome, requested to add a few slides on the usage of the command line `grep` utility (its options, basic usage etc.) cuz it's essential.

Homework assignment still needs to be done.

**Comment by Lesi-N** [comment]
Added slides to regex presentation, created pr on my repo with homework

**Comment by last-genius** [comment]
Thanks for the slides on `grep`, left a comment on the PR! Closing this then...
