### ISSUE TITLE
Git and GitHub (History, reasons of existence. Add Commit Push, Forks. How to hand over  homework)

### ISSUE THREAD

**Issue by Myralllka** [ucu-computer-science/UCU_Linux_Club#38]
make presentation + presentation notes + create homework

**Comment by last-genius** [comment]
Reviewed the presentation, it is currently being reworked (I wasn't really into the order of progression `github -> git basics -> branches`).

**Comment by last-genius** [comment]
Presentation is fine, discussed the homework assignment too!
