### ISSUE TITLE
LFHS (The Linux filesystem hierarchy standard)

### ISSUE THREAD

**Issue by Myralllka** [ucu-computer-science/UCU_Linux_Club#40]
make presentation + presentation notes + create homework

**Comment by Adeon18** [comment]
Added notes to Google drive in "Ostap :D" directory. (Up for feedback)

**Comment by last-genius** [comment]
Reviewed the lecture notes, added a few comments in the Google Doc. Nice work!

Just a few things to keep in mind: 
1. Emphasize that these directories are named in a human-understandable way and the students don't really have to remember what's in every directory at once
2. Show them how to find the information on these directories, how to interact with the ones that have specific use cases (i.e. mapped devices, processes etc.)

**Comment by Adeon18** [comment]
Presentation done! (Only last slide with homework is absent). Also made some tweaks to the notes as well as clearly stated which directories I will be going in during presentation.

**Comment by last-genius** [comment]
Reviewed the presentation, and it's awesome! Thank you! Any thoughts on homework yet?

**Comment by Adeon18** [comment]
Added "beta" version of homework to google docs.

**Comment by Myralllka** [comment]
Now I reviewed the presentation, and I have few remarks.
- :ToFix: Neither presentation nor notes contain a description of WHAT is the LFHS and why we need it
- :ToFix: Resolution of the example is really too low
- :ToCheck: Contains wrong information... according to manuals everything is OK, BUT... I double-checked it on two different fresh-installed Linux-based systems Ubuntu and Arch... I can not find any info at the internet, but according to my experiments /bin -> /usr/bin; /lib->/usr/lib; and with small differences also /slib, /lib64; on UBUNTU also /lib32, lsbx32 are symlinks. Please if there will be some time, check it, that is interesting
