### ISSUE TITLE
Vim (basic commands, why we need it, extensions) Tmux (why we need it, how to use it)

### ISSUE THREAD

**Issue by Myralllka** [ucu-computer-science/UCU_Linux_Club#44]
make presentation + presentation notes + create homework

**Comment by Myralllka** [comment]
Also, I totally recommend adding one more topic - shell and WHY we use it (not how). For example, the importance of scripting and automating. Show some features of autocompletion, git integration with oh-my-zsh and staff like that. @fox-flex @last-genius

**Comment by last-genius** [comment]
Clarification: just start the presentation with a few slides to remind them that the shell is not that scary, that it's important for scripting and automation, etc.

Also that it's quite easy to modify it and add syntax highlighting, fuzzy searching, tab auto-completion etc. (oh-my-zsh, fzf....)
