### ISSUE TITLE
Package managers

### ISSUE THREAD

**Issue by Myralllka** [ucu-computer-science/UCU_Linux_Club#45]
make presentation + presentation notes + create homework

**Comment by Lesi-N** [comment]
Presentation is up for review on Drive
Homework is TBD, though they've definitely installed packages until now, soooo

**Comment by last-genius** [comment]
Reviewed the presentation, don't think we really need a homework assignment for this one, yeah

**Comment by Lesi-N** [comment]
Made requested changes
